cat1 = 'PPT';
  var numfeed = 6;
  var startfeed = 2;
  var urlblog = "https://powerpoint.adrkha.com/";
  var charac = 0;
  var urlprevious, urlnext;function arlinafeed(e,t){for(var n=e.split("<"),r=0;r<n.length;r++)-1!=n[r].indexOf(">")&&(n[r]=n[r].substring(n[r].indexOf(">")+1,n[r].length));return n=n.join(""),n=n.substring(0,t-1)}function showrecentpostsae(e){var t,n,r,a,i,s="";urlprevious="",urlnext="";for(var l=0;l<e.feed.link.length;l++)"previous"==e.feed.link[l].rel&&(urlprevious=e.feed.link[l].href),"next"==e.feed.link[l].rel&&(urlnext=e.feed.link[l].href);for(var d=0;d<numfeed&&d!=e.feed.entry.length;d++){t=e.feed.entry[d],n=t.title.$t;for(var l=0;l<t.link.length;l++)if("alternate"==t.link[l].rel){r=t.link[l].href;break}
i="content"in t?t.content.$t:"summary"in t?t.summary.$t:"",a="media$thumbnail"in t?t.media$thumbnail.url:"//cdn.statically.io/gh/ibrahim5mohamed/powerpoint/14b08e3c/adrkha-ppt-blank.svg",s+="<div class='recentpostel'>",
s+="<a class='mb' href='"+r+"' title='"+n+"' target='_blank'><img alt='"+n+"' fetchpriority='high' height='215' width='383' src="+a.replace("s72-c","s450-rw-e365")+" title='"+n+"'/></a>",s+="<h1><a href='"+r+"' title='"+n+"' target='_blank'>"+n+"</a></h1>",s+="<p>"+arlinafeed(i,charac)+"</p>",s+="</div>"}
document.getElementById("recentpostsae").innerHTML=s,s="",s+=urlprevious?"<a href='javascript:navigasifeed(-1);' class='previous' title='السابق'>السابق</a>":"<span class='noactived previous'>السابق</i></span>",s+=urlnext?"<a href='javascript:navigasifeed(1);' class='next' title='التالي'>التالي</i></a>":"<span class='noactived next'>التالي</i></span>",s+="<a href='javascript:navigasifeed(0);' class='home' title='الصفحة الأولى'>↻</i></a>",document.getElementById("recentpostnavfeed").innerHTML=s}function navigasifeed(e){var t,n;-1==e?(t=urlprevious.indexOf("?"),n=urlprevious.substring(t)):1==e?(t=urlnext.indexOf("?"),n=urlnext.substring(t)):n="?start-index=1&max-results="+numfeed+"&orderby=published&alt=json-in-script",n+="&callback=showrecentpostsae",incluirscript(n)}function incluirscript(e){1==startfeed&&removerscript(),document.getElementById("recentpostsae").innerHTML="<div id='recentpostload'></div>",document.getElementById("recentpostnavfeed").innerHTML="";var t=urlblog+"/feeds/posts/default/-/"+cat1+""+e,n=document.createElement("script");n.setAttribute("type","text/javascript"),n.setAttribute("src",t),n.setAttribute("id","arlinalabel"),document.getElementsByTagName("head")[0].appendChild(n),startfeed=1}function removerscript(){var e=document.getElementById("arlinalabel"),t=e.parentNode;t.removeChild(e)}onload=function(){navigasifeed(0)};
